### 비동기 코드에 대한 오류 처리 방법 

async/await 핸들러 함수를 사용하여 라우터를 실행하면 앱이 충돌하며 종료된다. 
> [nodemon] app crashed - waiting for file changes before starting...

<br>

[방법 1] try/catch 블록을 포함하도록 수정하면 앱이 계속 실행된다. 

```javascript
export const tempAsyncException = async (req, res, next) => {
    try {
        throw new BaseError(status.BAD_REQUEST);
    } catch (err) {
        next(err);
    }
};
```

그러나 매번 try/catch 블록을 사용하는 것이 번거롭다면, [방법 2] try/catch 블록을 포함하는 wrapper 함수를 만들 수 있다.

```javascript
export const handleCall = (callback) => {
    return async (req, res, next) => {
        try {
            await callback(req, res, next);
        } catch (err) {
            next(err);
        }
    };
};
```

```javascript
export const tempAsyncException = handleCall(async (req, res, next) => {
    throw new BaseError(status.BAD_REQUEST);
});
```

<br>

### 참고

https://betterprogramming.pub/two-error-handling-methods-for-asynchronous-code-in-express-js-72feb82d4f2
